### ISSUE TITLE
"webhook_secret" Meaning

### ISSUE THREAD

**Issue by serwer20** [au5ton/serverless-bot#7]
Hello,
I'm stuck with config.json

I don't understand "webhook_secret" meaning? What should I use here?

```
{
    "telegram": {
        "bot_token": "1111111111:AAGBZpfsgsfhsXXXXXXXXX1D41DgUxI",
        "webhook_secret": "????????????"  // <<<<<<<<
    },
    "gcp": {
        "datacenter": "europe-west1",
        "project_id": "project-id-here"
    }
}
```

Regards!

**Comment by au5ton** [comment]
https://github.com/au5ton/serverless-bot/blob/5df694733ec8c5b380f36c9e50e63323c55ae68e/functions/src/lib/bot/route.js#L1-L7

`webhook_secret` denotes the url path by which the endpoint will be listening to to accept webhook requests.

From https://core.telegram.org/bots/api#setwebhook

> If you'd like to make sure that the Webhook request comes from Telegram, we recommend using a secret path in the URL, e.g. https://www.example.com/<token>. Since nobody else knows your bot's token, you can be pretty sure it's us.

It's an arbitrary "password" to your bot that can be as simple or complicated as you want it to be.
